{
    "docs": "https://docs.ansible.com/ansible-core/2.18/dev_guide/testing/sanity/pep8.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test pep8` [[explain](https://docs.ansible.com/ansible-core/2.18/dev_guide/testing/sanity/pep8.html)] failed with 6 errors:", 
            "output": "plugins/filter/generalized_time_to_epoch.py:64:1: W391: blank line at end of file\nplugins/module_utils/dsldap.py:235:1: W391: blank line at end of file\nplugins/modules/ds_repl_binddn_auth.py:139:1: W391: blank line at end of file\nplugins/modules/ds_repl_enable.py:166:1: W391: blank line at end of file\nplugins/modules/ds_repl_init.py:150:1: W391: blank line at end of file\nplugins/modules/ds_repl_manager.py:144:1: W391: blank line at end of file"
        }
    ], 
    "verified": false
}
